# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# adityalella
#ci build

name: $(Build.DefinitionName)_$(Build.DefinitionVersion)_$(Build.BuildId)_$(Build.BuildNumber)_$(My.Variable)

resources:
  repositories:
  - repository: dotnet
    type: github
    name: adityaldevops/donet
    endpoint: aditya

  pipelines:
  - pipeline: dotnetpipeline # Name of the pipeline resource.
    source: adityaldevops.donet # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes

trigger: 
- master

pool: adpool

variables:
  buildConfiguration: 'Release'
  buildPlatform: '64x'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- bash: echo "dotnetpipeline runs after security-lib-ci completes" 



#- task: PublishCodeCoverageResults@1
  #inputs:
    #codeCoverageTool: "JaCoCo"
    #summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
    #reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
    #failIfCoverageEmpty: true
