# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# adityalella

resources:
  repositories:
  - repository: dotnet
    type: github
    endpoint: aditya
    name: adityaldevops/dotnet

trigger: 
- master

pool: adpool

variables:
  buildConfiguration: 'Release'
  buildPlatform: '64x'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
